name: Docker

on:
  workflow_call:

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Docker build
      uses: docker/setup-buildx-action@v3.7.1

    - name: Docker Login
      uses: docker/login-action@v3.3.0
      with:
        username: mattheusstefan
        password: ${{secrets.PASSWORD_DOCKER_HUB}}

    - name: Build and push Docker images
      uses: docker/build-push-action@v6.9.0
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: mattheusstefan/go_ci:${{github.ref_name}}

              
      
