name: Docker

on:
  workflow_call:

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Docker build
      uses: docker/setup-buildx-action@v3.7.1

    - name: Docker Login
      uses: docker/login-action@v3.3.0
      with:
        username: mattheusstefan
        password: ${{secrets.PASSWORD_DOCKER_HUB}}
      
